
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blocmetrics_dev

test:
  <<: *default
  database: blocmetrics_test

staging:
  <<: *default
  database: blocmetrics_staging

production:
  <<: *default
  database: blocmetrics_prod
  host: /tmp
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
